load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "internal",
    srcs = glob(["*.go"]),
    importpath = "github.com/DaliborDev/monorepo/pulse/internal",
    visibility = ["//visibility:public"]
)