services:
#  proxy:
#    container_name: proxy
#    image: nginx:1.25.4
#    ports:
#      - "8080:80"
#    restart: always

  pulse:
    container_name: pulse
    working_dir: /workspace
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./pulse:/workspace/pulse
    restart: always
    command: >
      bash -c "bazel run //pulse:run -- --interval 3m"