services:
#  proxy:
#    container_name: proxy
#    image: nginx:1.25.4
#    ports:
#      - "8080:80"
#    restart: always

  pulse:
    container_name: pulse
    working_dir: /workspace
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./pulse:/workspace/pulse
    restart: always
    command: >
      bash -c "bazel run //pulse:run -- --interval 3s"

#  mysql:
#    container_name: mysql
#    image: mysql:8.2.0
#    cap_add:
#      - SYS_NICE
#    environment:
#      - MYSQL_DATABASE=db01
#      - MYSQL_ROOT_PASSWORD=najzajebanijasifranasvetu
#    ports:
#      - "3306:3306"
#    restart: always

volumes:
  db:
    driver: local